import type { Metadata } from "next";

import "./globals.scss";
import { StoreProvider } from "./StoreProvider";
import Header from "@/shared/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="html" lang="en">
      <body className="body">
        <main className="main">
          <StoreProvider>
            <Header />
            {children}
          </StoreProvider>
        </main>
      </body>
    </html>
  );
}
